server:
  port: 8090
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-server-service:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: ms-vehicle
          uri: lb://ms-vehicle
          predicates:
            - Path=/vehicle/**
        - id: ms-vehicle-brand
          uri: lb://ms-vehicle
          predicates:
            - Path=/brand/**
        - id: ms-repair
          uri: lb://ms-repair
          predicates:
            - Path=/repair/**
        - id: ms-repairlist
          uri: lb://ms-repairlist
          predicates:
            - Path=/repair-list/**
        - id: ms-report
          uri: lb://ms-report
          predicates:
            - Path=/report/**
