server:
  port: 8093
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  # jpa:
  #   hibernate:
  #     ddl-auto: create # Opciones: create, update, create-drop, validate
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       format_sql: true
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
