apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-report-deployment
  labels:
    app: ms-report-deployment
spec:
  selector:
    matchLabels:
      app: ms-report-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-report-deployment
    spec:
      containers:
        - name: ms-report
          image: mieres/ms-report
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REPORT
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REPORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_REPORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD
